chore: improve failed tag creation diagnostics

diff --git a/auto-tagging/action.yml b/auto-tagging/action.yml
--- a/auto-tagging/action.yml
+++ b/auto-tagging/action.yml
@@ -78,9 +78,11 @@ runs:
         # Workflow outputs
         cat <<EOF | tee -a ${GITHUB_STEP_SUMMARY} | tee -a ${GITHUB_OUTPUT}
         new_tag=$NEW_TAG
+        latest_tag=$LATEST_TAG
         EOF
 
     - name: Create tag
+      id: create-tag
       uses: actions/github-script@v5
       env:
         NEW_TAG: '${{ steps.generate-tag.outputs.new_tag }}'
@@ -99,3 +101,27 @@ runs:
             ref: `refs/tags/${newTag}`,
             sha: context.sha
           })
+
+    # the command `git describe --tags --abbrev=0 2>/dev/null || true` cannot handle multiple tags for the same commit
+    # for example, if the commit has tags v1.0.0 and v1.0.1, the command will return v1.0.0 and the create-tag step will fail
+    - name: Check for multiple tags
+      shell: bash -l -ET -eo pipefail {0}
+      if: steps.create-tag.outcome == 'failure'
+      env:
+        LATEST_TAG: ${{ steps.generate-tag.outputs.latest_tag }}
+      run: |
+        # Fetch tags associated with the commit pointed to by $LATEST_TAG
+        TAG_COUNT=$(git --no-pager tag --points-at "$LATEST_TAG" | wc -l | tr -d ' ')
+
+        if [[ "$TAG_COUNT" -gt 1 ]]; then
+          echo "❌ Error: Multiple tags ($TAG_COUNT) found pointing at commit $LATEST_TAG. Please delete invalid tags."
+          git --no-pager tag --points-at "$LATEST_TAG"
+          exit 1
+        elif [[ "$TAG_COUNT" -eq 0 ]]; then
+          echo "⚠️ Warning: No tags detected pointing at commit $LATEST_TAG."
+          exit 1
+        else
+          TAG_NAME=$(git --no-pager tag --points-at "$LATEST_TAG")
+          echo "✅ Exactly one tag ($TAG_NAME) detected. The failure might not be related to duplicated tags."
+          exit 0
+        fi
