overlays

diff --git a/.github/workflows/build-python-ai-scores.yaml b/.github/workflows/build-python-ai-scores.yaml
--- a/.github/workflows/build-python-ai-scores.yaml
+++ b/.github/workflows/build-python-ai-scores.yaml
@@ -37,80 +37,80 @@ on:
 
 jobs:
 
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - id: init
-        name: Init Job
-        uses: hawk-ai-aml/github-actions/job-init@python-ai-scores
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - uses: actions/checkout@v3
-      - uses: actions/setup-python@v4
-        with:
-          python-version: 3.8
-
-      - name: Install pipenv
-        run: pip install pipenv
-
-      - name: Run Pytest
-        env:
-          JENKINS: true
-          IS_JENKINS: true
-          AWS_ACCESS_KEY_ID: ${{ secrets.BACKEND_FILE_AWS_ACCESS_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKEND_FILE_AWS_SECRET_ACCESS_KEY }}
-        run: |
-          pipenv install --dev
-          pipenv requirements --dev > requirements.txt
-          pipenv run pip install -r manual-requirements.txt
-      #          pipenv run pytest tests --junitxml=report.xml
-      #          pipenv run junit2html report.xml report.html
-      #          mkdir report-dir && mv report.html ./report-dir/report.html
-
-      #      - name: Upload Reports to S3
-      #        id: reports
-      #        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
-      #        uses: hawk-ai-aml/upload-s3-action@master
-      #        with:
-      #          aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
-      #          aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
-      #          aws_bucket: github-actions-static-html-2
-      #          source_dir: ./report-dir
-      #          destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
-          aws-region: ${{ inputs.profile == 'nab' && 'us-east-1' || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY && 'eu-central-1' }}
-          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
-
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
-        with:
-          registries: ${{ inputs.profile == 'nab' && 569345997196 || 860641649575 }}
-
-      - name: Build and tag images
-        env:
-          MODULES: ${{ inputs.modules-string }}
-          REGISTRY: ${{ inputs.profile == 'nab' && '569345997196.dkr.ecr.us-east-1.amazonaws.com' || '860641649575.dkr.ecr.eu-central-1.amazonaws.com' }}
-        run: |
-          echo $MODULES
-          for module in $MODULES
-          do
-            REPOSITORY_FOLDER=$(echo ${module} | sed 's/\_/\-/g')
-            REPOSITORY_FULL_NAME="$REGISTRY/ai-scores-${REPOSITORY_FOLDER}"
-            TAG=$(echo ${GITHUB_REF_NAME} | sed 's,\/,-,g; s,\#,,g')
-            echo "$REPOSITORY_FULL_NAME is building..."
-            DOCKER_BUILDKIT=1 docker build --build-arg SERVICE=${module} -t ${REPOSITORY_FULL_NAME}:${TAG} .
-            docker push ${REPOSITORY_FULL_NAME}:${TAG}
-          done
+#  build:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - id: init
+#        name: Init Job
+#        uses: hawk-ai-aml/github-actions/job-init@python-ai-scores
+#
+#      - name: Login to Docker Hub
+#        uses: docker/login-action@v2
+#        with:
+#          username: ${{ secrets.DOCKERHUB_USERNAME }}
+#          password: ${{ secrets.DOCKERHUB_TOKEN }}
+#
+#      - uses: actions/checkout@v3
+#      - uses: actions/setup-python@v4
+#        with:
+#          python-version: 3.8
+#
+#      - name: Install pipenv
+#        run: pip install pipenv
+#
+#      - name: Run Pytest
+#        env:
+#          JENKINS: true
+#          IS_JENKINS: true
+#          AWS_ACCESS_KEY_ID: ${{ secrets.BACKEND_FILE_AWS_ACCESS_ID }}
+#          AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKEND_FILE_AWS_SECRET_ACCESS_KEY }}
+#        run: |
+#          pipenv install --dev
+#          pipenv requirements --dev > requirements.txt
+#          pipenv run pip install -r manual-requirements.txt
+#      #          pipenv run pytest tests --junitxml=report.xml
+#      #          pipenv run junit2html report.xml report.html
+#      #          mkdir report-dir && mv report.html ./report-dir/report.html
+#
+#      #      - name: Upload Reports to S3
+#      #        id: reports
+#      #        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
+#      #        uses: hawk-ai-aml/upload-s3-action@master
+#      #        with:
+#      #          aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
+#      #          aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
+#      #          aws_bucket: github-actions-static-html-2
+#      #          source_dir: ./report-dir
+#      #          destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
+#
+#      - name: Configure AWS credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
+#          aws-region: ${{ inputs.profile == 'nab' && 'us-east-1' || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY && 'eu-central-1' }}
+#          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
+#
+#      - name: Login to Amazon ECR
+#        id: login-ecr
+#        uses: aws-actions/amazon-ecr-login@v1
+#        with:
+#          registries: ${{ inputs.profile == 'nab' && 569345997196 || 860641649575 }}
+#
+#      - name: Build and tag images
+#        env:
+#          MODULES: ${{ inputs.modules-string }}
+#          REGISTRY: ${{ inputs.profile == 'nab' && '569345997196.dkr.ecr.us-east-1.amazonaws.com' || '860641649575.dkr.ecr.eu-central-1.amazonaws.com' }}
+#        run: |
+#          echo $MODULES
+#          for module in $MODULES
+#          do
+#            REPOSITORY_FOLDER=$(echo ${module} | sed 's/\_/\-/g')
+#            REPOSITORY_FULL_NAME="$REGISTRY/ai-scores-${REPOSITORY_FOLDER}"
+#            TAG=$(echo ${GITHUB_REF_NAME} | sed 's,\/,-,g; s,\#,,g')
+#            echo "$REPOSITORY_FULL_NAME is building..."
+#            DOCKER_BUILDKIT=1 docker build --build-arg SERVICE=${module} -t ${REPOSITORY_FULL_NAME}:${TAG} .
+#            docker push ${REPOSITORY_FULL_NAME}:${TAG}
+#          done
 
   update-overlays:
     needs: build
@@ -165,7 +165,8 @@ jobs:
           bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
           EOF
           # End prepare SSH
-          git clone ${{ inputs.kustomize-repo }} kustomize
+          # git clone ${{ inputs.kustomize-repo }} kustomize
+          git clone ${{ inputs.kustomize-repo }}
           cd kustomize/${KUSTOMIZE_PATH}/overlays/${OVERLAY}
           # https://hawkai.atlassian.net/browse/SRE-629
           # this relies that all nab overlays are called nab-dev
