Feature/sre 454 (#12)
Co-authored-by: Vu Nguyen <vu.nguyenduy@hawkai.tech>

diff --git a/.github/workflows/build-reactjs.yaml b/.github/workflows/build-reactjs.yaml
--- a/.github/workflows/build-reactjs.yaml
+++ b/.github/workflows/build-reactjs.yaml
@@ -36,7 +36,6 @@ jobs:
           component: ${{ inputs.component }}
           update-kustomize: ${{ inputs.updateKustomize }}
           overlays: ${{ inputs.kustomizeOverlays }}
-          skip-tests: ${{ inputs.skipTests }}
 
   build:
     needs: [ init ]
@@ -71,105 +70,105 @@ jobs:
           cmd: test
 
       - name: Yarn build
-      - uses: borales/actions-yarn@v3.0.0
+        uses: borales/actions-yarn@v3.0.0
         with:
           cmd: build
 
-      - name: Upload Reports to S3
-        id: reports
-        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
-        uses: hawk-ai-aml/upload-s3-action@master
-        with:
-          aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
-          aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
-          aws_bucket: github-actions-static-html-2
-          source_dir: app/build/reports
-          destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
-
-      - name: Provide Links to Reports
-        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
-        run: |
-          echo "### Test Reports" | tee -a ${GITHUB_STEP_SUMMARY}
-          report_url=https://github-actions-static-html-2.s3.amazonaws.com/${{ github.event.repository.name }}-${{ github.run_id }}/
-          for report_file_loc in ${{ join(fromJSON(steps.reports.outputs.object_locations), ' ') }}; do
-            report_basename=${report_file_loc##${report_url}}
-            if [[ ${report_file_loc} == */main.html || ${report_file_loc} == */index.html || ${report_file_loc} == */licenseReport.html ]]; then
-              echo "* [${report_basename}](${report_file_loc})" | tee -a ${GITHUB_STEP_SUMMARY}
-            fi
-          done
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
-          aws-region: ${{ fromJson(needs.init.outputs.metadata).ecr.region }}
-
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
-        with:
-          registries: ${{ fromJson(needs.init.outputs.metadata).ecr.registry }}
-
-      - name: Build image
-        run: |
-          docker build --no-cache -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }}
-          aws ecr get-login-password --region eu-central-1 docker | login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}.dkr.ecr.eu-central-1.amazonaws.com
-
-      - name: Push Image
-        id: push-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ fromJson(needs.init.outputs.metadata).ecr.repository }}
-        run: |
-          export DOCKER_CLI_EXPERIMENTAL=enabled
-
-          set +e
-          docker manifest inspect ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }} 2>&1> /dev/null
-          inspect_code=$?
-          set -e
-
-          if [[ "${inspect_code}" != 0 ]]; then  
-            docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }}
-          fi
-
-  update-overlays:
-    needs: [ init, build ]
-    if: ${{ needs.init.outputs.update-kustomize == 'true' }}
-    runs-on: [ "self-hosted", "builder" ]
-    strategy:
-      # Avoid race condition issues with github
-      max-parallel: 1
-      matrix:
-        overlay: ${{fromJson(needs.init.outputs.overlays)}}
-
-    steps:
-      - id: init
-        name: Init Job
-        uses: hawk-ai-aml/job-init@master
-
-      - id: udpate-overlay-github
-        name: Update kustomize overlay
-        if: fromJson(needs.init.outputs.parameters).kustomize == 'github' || fromJson(needs.init.outputs.parameters).kustomize == 'github-fake'
-        uses: hawk-ai-aml/github-actions/kustomize-overlay@master
-        with:
-          component-metadata: ${{ needs.init.outputs.metadata }}
-          component-overlay: ${{ matrix.overlay }}
-          component-tag: ${{ env.HAWK_IMAGE_TAG }}
-          kustomize-repo: ${{ fromJson(needs.init.outputs.parameters).kustomize == 'github-fake' && 'hawk-ai-aml/kustomize2.git' || 'hawk-ai-aml/kustomize.git' }}
-          kustomize-access-token: ${{ secrets.REPO_ACCESS_PAT }}
-          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
-
-      - id: udpate-overlay-bitbucket
-        name: Update kustomize overlay
-        if: fromJson(needs.init.outputs.parameters).kustomize == 'bitbucket' || fromJson(needs.init.outputs.parameters).kustomize == 'bitbucket-fake'
-        uses: hawk-ai-aml/github-actions/kustomize-overlay-ssh@master
-        with:
-          component-metadata: ${{ needs.init.outputs.metadata }}
-          component-overlay: ${{ matrix.overlay }}
-          component-tag: ${{ env.HAWK_IMAGE_TAG }}
-          kustomize-repo: ${{ fromJson(needs.init.outputs.parameters).kustomize == 'bitbucket-fake' && 'git@bitbucket.org:hawkai/kustomize2.git' || 'git@bitbucket.org:hawkai/kustomize.git' }}
-          kustomize-ssh-key: ${{ secrets.KUSTOMIZE_DEPLOY_PRIVATE_KEY }}
-          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
+#      - name: Upload Reports to S3
+#        id: reports
+#        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
+#        uses: hawk-ai-aml/upload-s3-action@master
+#        with:
+#          aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
+#          aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
+#          aws_bucket: github-actions-static-html-2
+#          source_dir: app/build/reports
+#          destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
+#
+#      - name: Provide Links to Reports
+#        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
+#        run: |
+#          echo "### Test Reports" | tee -a ${GITHUB_STEP_SUMMARY}
+#          report_url=https://github-actions-static-html-2.s3.amazonaws.com/${{ github.event.repository.name }}-${{ github.run_id }}/
+#          for report_file_loc in ${{ join(fromJSON(steps.reports.outputs.object_locations), ' ') }}; do
+#            report_basename=${report_file_loc##${report_url}}
+#            if [[ ${report_file_loc} == */main.html || ${report_file_loc} == */index.html || ${report_file_loc} == */licenseReport.html ]]; then
+#              echo "* [${report_basename}](${report_file_loc})" | tee -a ${GITHUB_STEP_SUMMARY}
+#            fi
+#          done
+#
+#      - name: Configure AWS credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
+#          aws-region: ${{ fromJson(needs.init.outputs.metadata).ecr.region }}
+#
+#      - name: Login to Amazon ECR
+#        id: login-ecr
+#        uses: aws-actions/amazon-ecr-login@v1
+#        with:
+#          registries: ${{ fromJson(needs.init.outputs.metadata).ecr.registry }}
+#
+#      - name: Build image
+#        run: |
+#          docker build --no-cache -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }}
+#          aws ecr get-login-password --region eu-central-1 docker | login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}.dkr.ecr.eu-central-1.amazonaws.com
+#
+#      - name: Push Image
+#        id: push-image
+#        env:
+#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#          ECR_REPOSITORY: ${{ fromJson(needs.init.outputs.metadata).ecr.repository }}
+#        run: |
+#          export DOCKER_CLI_EXPERIMENTAL=enabled
+#
+#          set +e
+#          docker manifest inspect ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }} 2>&1> /dev/null
+#          inspect_code=$?
+#          set -e
+#
+#          if [[ "${inspect_code}" != 0 ]]; then
+#            docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }}
+#          fi
+#
+#  update-overlays:
+#    needs: [ init, build ]
+#    if: ${{ needs.init.outputs.update-kustomize == 'true' }}
+#    runs-on: [ "self-hosted", "builder" ]
+#    strategy:
+#      # Avoid race condition issues with github
+#      max-parallel: 1
+#      matrix:
+#        overlay: ${{fromJson(needs.init.outputs.overlays)}}
+#
+#    steps:
+#      - id: init
+#        name: Init Job
+#        uses: hawk-ai-aml/job-init@master
+#
+#      - id: udpate-overlay-github
+#        name: Update kustomize overlay
+#        if: fromJson(needs.init.outputs.parameters).kustomize == 'github' || fromJson(needs.init.outputs.parameters).kustomize == 'github-fake'
+#        uses: hawk-ai-aml/github-actions/kustomize-overlay@master
+#        with:
+#          component-metadata: ${{ needs.init.outputs.metadata }}
+#          component-overlay: ${{ matrix.overlay }}
+#          component-tag: ${{ env.HAWK_IMAGE_TAG }}
+#          kustomize-repo: ${{ fromJson(needs.init.outputs.parameters).kustomize == 'github-fake' && 'hawk-ai-aml/kustomize2.git' || 'hawk-ai-aml/kustomize.git' }}
+#          kustomize-access-token: ${{ secrets.REPO_ACCESS_PAT }}
+#          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
+#
+#      - id: udpate-overlay-bitbucket
+#        name: Update kustomize overlay
+#        if: fromJson(needs.init.outputs.parameters).kustomize == 'bitbucket' || fromJson(needs.init.outputs.parameters).kustomize == 'bitbucket-fake'
+#        uses: hawk-ai-aml/github-actions/kustomize-overlay-ssh@master
+#        with:
+#          component-metadata: ${{ needs.init.outputs.metadata }}
+#          component-overlay: ${{ matrix.overlay }}
+#          component-tag: ${{ env.HAWK_IMAGE_TAG }}
+#          kustomize-repo: ${{ fromJson(needs.init.outputs.parameters).kustomize == 'bitbucket-fake' && 'git@bitbucket.org:hawkai/kustomize2.git' || 'git@bitbucket.org:hawkai/kustomize.git' }}
+#          kustomize-ssh-key: ${{ secrets.KUSTOMIZE_DEPLOY_PRIVATE_KEY }}
+#          aws-access-key-id: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_ACCESS_KEY_ID || secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ inputs.profile == 'nab' && secrets.AWS_NAB_DEV_ECR_SECRET_ACCESS_KEY || secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
