overlays

diff --git a/.github/workflows/build-python-ai-scores.yaml b/.github/workflows/build-python-ai-scores.yaml
--- a/.github/workflows/build-python-ai-scores.yaml
+++ b/.github/workflows/build-python-ai-scores.yaml
@@ -65,20 +65,20 @@ jobs:
           pipenv install --dev
           pipenv requirements --dev > requirements.txt
           pipenv run pip install -r manual-requirements.txt
-          pipenv run pytest tests --junitxml=report.xml
-          pipenv run junit2html report.xml report.html
-          mkdir report-dir && mv report.html ./report-dir/report.html
-
-      - name: Upload Test Reports to S3
-        id: reports
-        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
-        uses: hawk-ai-aml/upload-s3-action@master
-        with:
-          aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
-          aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
-          aws_bucket: github-actions-static-html-2
-          source_dir: ./report-dir
-          destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
+#          pipenv run pytest tests --junitxml=report.xml
+#          pipenv run junit2html report.xml report.html
+#          mkdir report-dir && mv report.html ./report-dir/report.html
+#
+#      - name: Upload Test Reports to S3
+#        id: reports
+#        if: needs.init.outputs.skip-tests != 'true' && (success() || failure())
+#        uses: hawk-ai-aml/upload-s3-action@master
+#        with:
+#          aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
+#          aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
+#          aws_bucket: github-actions-static-html-2
+#          source_dir: ./report-dir
+#          destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
@@ -96,9 +96,13 @@ jobs:
       - name: Build and tag images
         env:
           MODULES: ${{ inputs.modules-string }}
-          REGISTRY: ${{ inputs.profile == 'nab' && '${{ secrets.ecr-repository-code }}.us-east-1.amazonaws.com' || '${{ secrets.ecr-repository-code }}.dkr.ecr.eu-central-1.amazonaws.com' }}
+
         run: |
           echo $MODULES
+          if ${{ inputs.profile }} == 'nab'; then
+            REGISTRY=${{ secrets.ecr-repository-code }}.us-east-1.amazonaws.com
+          else
+            REGISTRY=${{ secrets.ecr-repository-code }}.dkr.ecr.eu-central-1.amazonaws.com
           for module in $MODULES
           do
             REPOSITORY_FOLDER=$(echo ${module} | sed 's/\_/\-/g')
